sudo: required
language: node_js
node_js:
  - 14

services:
  - docker

env:
  global:
    - MONGODB_URI=$MONGO_DB_URI
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-398721
  - gcloud config set compute/zone europe-north1-a
  - gcloud container clusters get-credentials ife-cluster
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker run -d -p 27017:27017 --name mongodb mongo:latest

before_script:
  - sleep 15

script:
  - cd ./app
  - npm install

after_success:
  - cd ../
  - docker build -t diadem27/to-do-app .
  - docker push diadem27/to-do-app

deploy:
  provider: gae
  keyfile: service-account.json.enc
  project: multi-k8s-398721
  on:
    branch: main
