language: node_js
node_js:
  - 14

services:
  - docker

env:
  global:
    - MONGODB_URI=$MONGO_DB_URI

before_install:
  - echo $DOCKER_ID
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker run -d -p 27017:27017 --name mongodb mongo:latest

before_script:
  - sleep 15

script:
  - cd ./app
  - npm install

after_success:
  - docker build -t diadem27/to-do-app .
  - docker push diadem27/to-do-app

deploy:
  provider: script 
  script: bash ./deploy.sh
  on:
    branch: main
