name: Create envfile

on: [ push ]

id: workflow_b

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: 'Create env file'
      run: |
          touch .env
          echo MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }} >> .env
          echo SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }} >> .env
          cat .env
