name: Test and Coverage Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  test-and-check-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: 'Create env file'
        run: |
          touch .env
          echo MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }} >> .env
          echo SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }} >> .env
          cat .env

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage
        run: npm test -- --coverage --collectCoverageFrom=src/**/*.js

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        env:
          NODE_ENV: development
          PORT: 6000
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./coverage/lcov.info

      - name: Check coverage percentage
        run: |
          sleep 60
          ACTUAL_COVERAGE=$(curl -s "https://codecov.io/api/gh/${{ github.repository }}/commits/${{ github.sha }}" | jq -r '.commit.totals.c')
          echo $ACTUAL_COVERAGE
          echo "Pull Request SHA ${{ github.event.pull_request.head.sha }}"
          if (( $(echo "$ACTUAL_COVERAGE >= $COVERAGE_THRESHOLD" | bc -l) )); then
            echo "Code coverage is within the threshold."
          else
            echo "Code coverage is below the threshold. Expected: $COVERAGE_THRESHOLD%, Actual: $ACTUAL_COVERAGE%"
          exit 1
          fi 

