name: Test and Coverage Check

on:
  push:
    branches:
      - main  

id: workflow_c

jobs:
  test-and-check-coverage:
    runs-on: ubuntu-latest
    needs: workflow_b

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage
        run: npm test -- --coverage --collectCoverageFrom=src/**/*.js

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        env:
          NODE_ENV: development
          PORT: 6000
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./coverage/lcov.info

      - name: Check coverage percentage
        run: |
          COVERAGE_THRESHOLD=70
          sleep 60
          ACTUAL_COVERAGE=$(curl -s "https://codecov.io/api/gh/${{ github.repository }}/commits/${{ github.sha }}" | jq -r '.commit.totals.c')
          echo $ACTUAL_COVERAGE
          if (( $(echo "$ACTUAL_COVERAGE >= $COVERAGE_THRESHOLD" | bc -l) )); then
            echo "Code coverage is within the threshold."
          else
            echo "Code coverage is below the threshold. Expected: $COVERAGE_THRESHOLD%, Actual: $ACTUAL_COVERAGE%"
          exit 1
          fi
